#!/bin/sh

set -e

# https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch
BRANCH="$(git symbolic-ref -q HEAD)"
BRANCH="${BRANCH##refs/heads/}"
BRANCH="${BRANCH:-HEAD}"

if [ "${BRANCH}" != "master" ]; then
  echo "i will deploy only from master branch for now"
  exit 1
fi

getProperty() {
  node -e "console.log(JSON.parse(require('fs').readFileSync('package.json')).$1)"
}

VERSION="$(git describe)"
PUBLIC_URL="$(getProperty deploy.publicUrl)"
MESSAGE="deployment of ${VERSION} to ${PUBLIC_URL}"

npm ci
npx parcel build src/todo.html --public-url "${PUBLIC_URL}"
git checkout gh-pages
rm * 1>&2 2>/dev/null || echo -n ''
cp dist/* ./
echo $VERSION > .version
git add .
git commit -m"${MESSAGE}"
git checkout "${BRANCH}"

./isRelease && npm version "${VERSION}-UP"